apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  namespace: dev
  labels:
    app: postgres
spec:
  nodeSelector:
    kubernetes.io/hostname: node01
  containers:
  - name: postgres
    image: postgres:16-alpine
    env:
    - name: POSTGRES_DB
      value: itemsdb
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: postgres
    ports:
    - containerPort: 5432
